### ISSUE TITLE
Design and develop "Home" tab of app

### ISSUE THREAD

**Issue by vayamdevindia** [Vayamdev/vayam-ui#2]
- Used design pdf.
- Created the Basic Home page skelaton as indicated in design pdf.
- Created directive for nav and footer bars.
- Created a standardized directive for image banner.
- Refactored carousel component.
- Added Vayam icon.

++ Update
- There should be a idea section on home and not idea tab.
- Get rid of home symbol.
- Projects list should be there on HOME page and it should be responsive.

**Comment by sanketjo96** [comment]
Completed
