### ISSUE TITLE
Design and develop "Gallery" link of app

### ISSUE THREAD

**Issue by vayamdevindia** [Vayamdev/vayam-ui#9]
- Use some npm pugin and implement photo gallery for vayam app.
- Look at the alignments of gallery thumbnails.

**Comment by vayamdevindia** [comment]
Noticed these things - 
- Clicking on image thumbnail is not opening gallery view (with lightbox) from that image. It is starting from first image.
- Some times opening the gallery view (with lightbox) is hiding the scrollbar on body so it become difficult to view the overflowed content of other tabs like Home.

**Comment by sanketjo96** [comment]
Done
